version: 2.1

orbs:
  ccinode: circleci/node@5

workflows:
  build:
    jobs:
      - ccinode/run:
          name: Build
          version: "16.18"
          resource_class: medium+
          npm-run: "ci:build"
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "*/dist"
                  - "*/*/dist"
                  - "*/*/*/dist"
                  - "*/build"
                  - "*/*/build"
                  - "*/*/*/build"
      - ccinode/run:
          name: Unit Tests
          requires:
            - Build
          version: "16.18"
          resource_class: medium
          setup:
            - attach_workspace:
                at: "."
          npm-run: "ci:test"
          post-steps:
            - store_test_results:
                path: "junit-reports"
            - store_artifacts:
                path: "junit-reports"
