version: 2.1

orbs:
  ccinode: circleci/node@dev:ceb0383ed3c5b425a7dca94eaed22d26de161717

workflows:
  build:
    jobs:
      - ccinode/run:
          name: Build
          version: "16.18"
          resource_class: small
          npm-run: "ci:build"
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "*/build"
                  - "*/tsconfig.tsbuildinfo"
      - ccinode/run:
          name: Unit Tests
          requires:
            - Build
          version: "16.18"
          resource_class: small
          setup:
            - attach_workspace:
                at: "."
          npm-run: "ci:test"
          post-steps:
            - store_test_results:
                path: "junit-reports"
            - store_artifacts:
                path: "junit-reports"

# VS Code Extension Version: 1.5.1